-- =========================================================================
-- Planning content import — extracted from the Ultimate Wedding Planning
-- Spreadsheet. Run ONCE after migration-003 (running twice = duplicates).
-- To start a sheet over: delete from planning_rows where sheet='checklist';
-- =========================================================================

-- checklist: 123 rows
insert into planning_rows (sheet, position, data) values
  ('checklist', 10, '{"done": false, "task": "CELEBRATE! YOU''RE ENGAGED!", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 20, '{"done": false, "task": "Arrange for families to meet, if possible", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 30, '{"done": false, "task": "Discuss and set a wedding budget", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 40, '{"done": false, "task": "Determine who will contribute to the budget and how much", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 50, '{"done": false, "task": "Start Researching Wedding Planners", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 60, '{"done": false, "task": "Narrow Down 2-3 Ideal Wedding Dates", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 70, '{"done": false, "task": "Create a Preliminary Guest List", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 80, '{"done": false, "task": "Design a mood board on pinterest or start saving photos/screenshots in a folder", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 90, '{"done": false, "task": "Start a Pinterest board and gather design inspiration", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 100, '{"done": false, "task": "Create a wedding email", "phase": "12+ Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 110, '{"done": false, "task": "Book Your Wedding Planner", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 120, '{"done": false, "task": "Research and book your ceremony venue", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 130, '{"done": false, "task": "Research and book your reception venue", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 140, '{"done": false, "task": "Choose your wedding party & invite them to celebrate with you", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 150, '{"done": false, "task": "Finalize the guest list and begin collecting addresses", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 160, '{"done": false, "task": "Create a wedding website", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 170, '{"done": false, "task": "Start your wedding registry", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 180, '{"done": false, "task": "Make arrangements for out of town guests- book hotel blocks", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 190, '{"done": false, "task": "Research and book your photographer", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 200, '{"done": false, "task": "Begin shopping for wedding dresses", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 210, '{"done": false, "task": "Look at your design/pinterest boards and start to narrow down your ideas based on common traits", "phase": "9-12 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 220, '{"done": false, "task": "Begin shopping for a wedding suit or tux", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 230, '{"done": false, "task": "Research caterers and begin requesting preliminary menu proposals", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 240, '{"done": false, "task": "Schedule menu tastings & book your caterer", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 250, '{"done": false, "task": "Schedule cake tastings & book", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 260, '{"done": false, "task": "Research and book your bartending company", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 270, '{"done": false, "task": "Research Required Event Insurance (if applicable)", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 280, '{"done": false, "task": "Research and book your videographer", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 290, '{"done": false, "task": "Finalize your wedding aesthetic and determine what floral items you want/need", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 300, '{"done": false, "task": "Research and book your florist", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 310, '{"done": false, "task": "Begin researching honeymoon options", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 320, '{"done": false, "task": "Choose your bridesmaid dresses or dress color and begin fittings", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 330, '{"done": false, "task": "Research and order save the dates", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 340, '{"done": false, "task": "Discuss ceremony & reception layout options- get floorplan from venue", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 350, '{"done": false, "task": "Discuss equipment, lighting, and decor options with your venue", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 360, '{"done": false, "task": "Research and book your ceremony music", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 370, '{"done": false, "task": "Research and book your cocktail hour music", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 380, '{"done": false, "task": "Research and book your reception music", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 390, '{"done": false, "task": "Finalize Wedding Dress/Suit & make the purchase!", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 400, '{"done": false, "task": "Shop for hair accessories, jewelry, shoes", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 410, '{"done": false, "task": "Send your design board to your wedding party and vendors", "phase": "6-9 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 420, '{"done": false, "task": "Decide on Groomsman Attire", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 430, '{"done": false, "task": "Research and book your bridal party, getaway, and/or guest transportation", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 440, '{"done": false, "task": "Confirm who needs wedding day styling, and research and book your hair and makeup artists", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 450, '{"done": false, "task": "Research and book your rehearsal dinner location", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 460, '{"done": false, "task": "Make honeymoon reservations", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 470, '{"done": false, "task": "Book your engagement photos and/or bridals and utilize your hair and makeup trial", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 480, '{"done": false, "task": "Book your wedding night accommodations", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 490, '{"done": false, "task": "Research stationery designers and order your wedding invitations", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 500, '{"done": false, "task": "Research and book your officiant", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb);
insert into planning_rows (sheet, position, data) values
  ('checklist', 510, '{"done": false, "task": "Book Event Rentals & Decor", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 520, '{"done": false, "task": "Book Your Cake Artists and/or Desserts if not already completed", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 530, '{"done": false, "task": "Book Rehearsal Dinner Venue", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 540, '{"done": false, "task": "Purchase Wedding Bands/Rings", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 550, '{"done": false, "task": "Research & Order Invitations", "phase": "4-5 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 560, '{"done": false, "task": "Schedule Wedding Dress Alterations", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 570, '{"done": false, "task": "Plan Welcome Bags for Guests", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 580, '{"done": false, "task": "Research & Order Favors", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 590, '{"done": false, "task": "Order Gifts for Bridal Party/Parents/Each Other", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 600, '{"done": false, "task": "Make a Wedding Playlist", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 610, '{"done": true, "task": "Finalize ALL rentals", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 620, '{"done": true, "task": "Send out Invitations- MAX 3 months before (destination) to MIN 6 Weeks before (local)", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 630, '{"done": true, "task": "Begin to Write Vows- consider doing this in a vow book so you aren''t reading off your phone on the wedding day; Custom Etsy Options or Affordable Amazon Option", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 640, '{"done": true, "task": "Design any Signage/Prints (ex: Menus, Ceremony Programs, Welcome Sign, Photos of You, etc.)", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 650, '{"done": false, "task": "Order Any Signage/Prints (ex: Menus, Ceremony Programs, Welcome Sign, Photos of You, etc.)", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 660, '{"done": true, "task": "Put Together Wedding Video or any printed photos you want for Reception", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 670, '{"done": true, "task": "Organize Bachelor/Bachelorette or any Pre-Wedding Parties", "phase": "2-3 Months", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 680, '{"done": true, "task": "One Month Meeting with Wedding Planner", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 690, '{"done": true, "task": "Order/Send Rehearsal Dinner Invites if you haven''t already", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 700, '{"done": true, "task": "Meet with your Officiant & Review the Ceremony", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 710, '{"done": true, "task": "Finalize Menu with Caterer", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 720, '{"done": true, "task": "Create Day-of Timeline & Send to Vendors", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 730, '{"done": true, "task": "Choose Specific Music (First Dance, Ceremony Processional, Parent Dances, etc)", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 740, '{"done": true, "task": "Obtain Marriage License (***only valid for 1 month and must be purchased in the county you''re getting married in)", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 750, '{"done": true, "task": "Final Dress/Suit Fittings", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 760, '{"done": true, "task": "Finalize Seating Chart/Place Cards/Escort Cards", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 770, '{"done": false, "task": "Confirm Honeymoon Bookings", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 780, '{"done": true, "task": "Ensure all RSVP''s are received- We recommend the RSVP date as 3-4 weeks before the wedding to ensure enough time to collect final #''s and provide final counts to vendors", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 790, '{"done": true, "task": "Send out as many payments as possible", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 800, '{"done": true, "task": "Decide on a Wet/Hot/Cold Weather Contingency Plan if Outdoors (Order Umbrellas, Blankets, Heaters if Necessary)", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 810, '{"done": true, "task": "Meet with Photographer/Videographer to Discuss Shot List & Final Details", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 820, '{"done": true, "task": "Organize Guest Book, Pens, Cake Servers, Toasting Flutes, Memorial Table, etc. (All Small, Personal Decor) Label it and put it in boxes to give to your Planner before the wedding", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 830, '{"done": true, "task": "Confirm all #''s and details with the Florist; including delivery/pickup/return times for florals and any rentals", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 840, '{"done": true, "task": "Submit any final counts to Caterer/Bar/Venue/Planner, etc depending on when deadlines are for these", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 850, '{"done": true, "task": "Arrange Wedding Ceremony Rehearsal", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 860, '{"done": false, "task": "Finalize Details for Rehearsal Dinner + Welcome Party", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 870, '{"done": true, "task": "Review Song List with Band/DJ/Assigned Music Person", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 880, '{"done": true, "task": "Get Hair Cut and/or Colored", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 890, '{"done": false, "task": "Assign Jobs to the Wedding Party", "phase": "3-6 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 900, '{"done": true, "task": "Confirm Cake Delivery Time & Location; If they are providing the cake stand, determine return policy", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 910, '{"done": false, "task": "Give Final Schedule to all Important Parties", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 920, '{"done": true, "task": "Confirm Any Last Vendor Delivery/Arrival Times", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 930, '{"done": true, "task": "Break in Wedding Shoes (& Pack Some Comfy Replacements!)", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 940, '{"done": false, "task": "Waxing/Threading/Tanning/Last of Beauty Treatments", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 950, '{"done": true, "task": "Finalize & Practice Vows", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 960, '{"done": false, "task": "Pack for your Honeymoon!!", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 970, '{"done": true, "task": "Find something old, new, borrowed & blue", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 980, '{"done": true, "task": "Put Together your own little Emergency Kit for the Wedding Day", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 990, '{"done": false, "task": "Remind Wedding Party of their jobs & give them a copy of the Wedding Day Timeline", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1000, '{"done": false, "task": "Finalize your Day-of Packing List & provide a copy to your planner", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb);
insert into planning_rows (sheet, position, data) values
  ('checklist', 1010, '{"done": false, "task": "Give/Finalize table decor to Venue or Planner & confirm how you want it displayed", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1020, '{"done": false, "task": "Pick up Wedding Dress/Suit/Tux (and other outfits if needed) - If Rented, Determine Return Date)", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1030, '{"done": false, "task": "Pay Any Outstanding Balances & Put Any Last Tips in Labeled Envelopes", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1040, '{"done": false, "task": "Determine Final Wedding Party Line Up for Ceremony & Reception Introductions", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1050, '{"done": false, "task": "Send out Wedding Day Timeline to any last vendors/important family members or friends", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1060, '{"done": true, "task": "Submit any final counts to Caterer/Bar/Venue/Planner, etc", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1070, '{"done": true, "task": "Get Your Ring(s) Cleaned!", "phase": "1-2 Weeks", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1080, '{"done": false, "task": "Give Vendor Tips to Planner (or someone you trust to give to the planner) to distribute on the day of", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1090, '{"done": false, "task": "Mani + Pedi", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1100, '{"done": false, "task": "Finish Packing for Honeymoon", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1110, '{"done": false, "task": "Deliver Welcome Bags to Hotel(s)", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1120, '{"done": false, "task": "Give out Wedding Party Accessories", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1130, '{"done": false, "task": "BREATHE!", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1140, '{"done": false, "task": "Enjoy time with Friends & Family in Town", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1150, '{"done": false, "task": "Attend Rehearsal + Dinner", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1160, '{"done": false, "task": "Drink Lots of Water!!", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1170, '{"done": false, "task": "Pack for your Honeymoon!!", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1180, '{"done": false, "task": "Pack a bag of wedding day essentials- including SNACKS!", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1190, '{"done": false, "task": "Get EXCITED :) You''re getting MARRIED TOMORROW!", "phase": "Day Before", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1200, '{"done": false, "task": "Drink Enough Water", "phase": "DAY OF!", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1210, '{"done": false, "task": "Eat Yummy Food", "phase": "DAY OF!", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1220, '{"done": false, "task": "Celebrate with your Friends & Family", "phase": "DAY OF!", "assigned": "", "completed": "", "notes": ""}'::jsonb),
  ('checklist', 1230, '{"done": false, "task": "MARRY YOUR BEST FRIEND!!", "phase": "DAY OF!", "assigned": "", "completed": "", "notes": ""}'::jsonb);

-- priorities: 103 rows
insert into planning_rows (sheet, position, data) values
  ('priorities', 10, '{"item": "Alcohol", "rank": "5 - ABSOLUTELY", "notes": "This is important to us and our guests. We would love to have an open bar but we don''t necessarily need to have a full bar."}'::jsonb),
  ('priorities', 20, '{"item": "Anniversary Dance", "rank": "5 - ABSOLUTELY", "notes": "We love the idea. I have seen a reverse anniversary dance that ends with everyone on the dance floor with the couple that I like a lot too. Or the idea of giving my bouqet to the winner of the anniversary dance instead of a toss"}'::jsonb),
  ('priorities', 30, '{"item": "Appetizers", "rank": "5 - ABSOLUTELY", "notes": "We love food. Also with an open bar food is important. We aren''t into super fancy appetizers we just want good food to be out and about before dinner"}'::jsonb),
  ('priorities', 40, '{"item": "Bachelor(ette) Parties", "rank": "5 - ABSOLUTELY", "notes": "We are both planning on having them! Since the wedding is going to be destination I think we are both planning to have lowkey ones to help with the cost to the wedding parties"}'::jsonb),
  ('priorities', 50, '{"item": "Bridal Party", "rank": "5 - ABSOLUTELY", "notes": "We have a massive bridal party right now. Might be able to make a few cuts but I don''t know."}'::jsonb),
  ('priorities', 60, '{"item": "Catering Service Style", "rank": "5 - ABSOLUTELY", "notes": "Buffet"}'::jsonb),
  ('priorities', 70, '{"item": "Ceremony", "rank": "5 - ABSOLUTELY", "notes": "Something short and sweet"}'::jsonb),
  ('priorities', 80, '{"item": "Dance Floor", "rank": "5 - ABSOLUTELY", "notes": "We would love a dance floor space but we do not need to bring in a fancy floor overlay or anything"}'::jsonb),
  ('priorities', 90, '{"item": "Dance Floor Time", "rank": "5 - ABSOLUTELY", "notes": "Dancing with our friends and family is very important to us"}'::jsonb),
  ('priorities', 100, '{"item": "Day of Coordinator", "rank": "5 - ABSOLUTELY", "notes": "Super hyped to have your there to help us on the day of the event!!"}'::jsonb),
  ('priorities', 110, '{"item": "DJ", "rank": "5 - ABSOLUTELY", "notes": ""}'::jsonb),
  ('priorities', 120, '{"item": "Dress", "rank": "5 - ABSOLUTELY", "notes": ""}'::jsonb),
  ('priorities', 130, '{"item": "Father // Daughter Dance", "rank": "5 - ABSOLUTELY", "notes": "My dad is super hyped about this"}'::jsonb),
  ('priorities', 140, '{"item": "First Dance", "rank": "5 - ABSOLUTELY", "notes": "We are going to take dance classes and I want it to be epic... Will is less excited but he will get there"}'::jsonb),
  ('priorities', 150, '{"item": "First Look", "rank": "5 - ABSOLUTELY", "notes": ""}'::jsonb),
  ('priorities', 160, '{"item": "First Look with Dad", "rank": "5 - ABSOLUTELY", "notes": "My dad and I aren''t super sentimental but I think we would both appreciate this moment"}'::jsonb),
  ('priorities', 170, '{"item": "Food", "rank": "5 - ABSOLUTELY", "notes": "This is a big priority for us! Everyone loves food. For food though it would be amazing if the caterer/venue could do a low/no lactose menu for us as Will is lactose intolerant. Also, I have a peanut allergy and Will is allergic to shellfish. We are a bit of a mess for food but we like a lot of different things"}'::jsonb),
  ('priorities', 180, '{"item": "Grand Entrance", "rank": "5 - ABSOLUTELY", "notes": "Nothing crazy but I want a fun enterance"}'::jsonb),
  ('priorities', 190, '{"item": "Grand Exit", "rank": "5 - ABSOLUTELY", "notes": "We want to do something fun and unique. Thinking maybe squirt guns or something funny"}'::jsonb),
  ('priorities', 200, '{"item": "Guest Experience", "rank": "5 - ABSOLUTELY", "notes": "We want everyone to have fun and no one to be stressed"}'::jsonb),
  ('priorities', 210, '{"item": "Honeymoon", "rank": "5 - ABSOLUTELY", "notes": "Thinking somewhere in Europe"}'::jsonb),
  ('priorities', 220, '{"item": "Indoors // Outdoors", "rank": "5 - ABSOLUTELY", "notes": "We would love access to both to be able to move inside and out throughout they day"}'::jsonb),
  ('priorities', 230, '{"item": "Invitations", "rank": "5 - ABSOLUTELY", "notes": "Will''s sister can help with these"}'::jsonb),
  ('priorities', 240, '{"item": "Location (City)", "rank": "5 - ABSOLUTELY", "notes": "We are so excited to be in the mountains for our big day"}'::jsonb),
  ('priorities', 250, '{"item": "Mother // Son Dance", "rank": "5 - ABSOLUTELY", "notes": "Will is a mamas boy"}'::jsonb),
  ('priorities', 260, '{"item": "Music", "rank": "5 - ABSOLUTELY", "notes": ""}'::jsonb),
  ('priorities', 270, '{"item": "Photographer", "rank": "5 - ABSOLUTELY", "notes": "The pictures are basically the only thing you keep from the day so this is important"}'::jsonb),
  ('priorities', 280, '{"item": "Registry", "rank": "5 - ABSOLUTELY", "notes": "I need to work on this but I am planning to put one together so people don''t get us random stuff"}'::jsonb),
  ('priorities', 290, '{"item": "Rehearsal", "rank": "5 - ABSOLUTELY", "notes": "The rehersal of the ceremony can be chill but it would be nice to practice. We will be doing a rehersal dinner with family and bridal party."}'::jsonb),
  ('priorities', 300, '{"item": "Save the Dates", "rank": "5 - ABSOLUTELY", "notes": "Will''s sister can help with these"}'::jsonb),
  ('priorities', 310, '{"item": "Seating Chart", "rank": "5 - ABSOLUTELY", "notes": "Doing this instead of place cards"}'::jsonb),
  ('priorities', 320, '{"item": "Sweetheart Table", "rank": "5 - ABSOLUTELY", "notes": "This over a headtable"}'::jsonb),
  ('priorities', 330, '{"item": "Table Numbers", "rank": "5 - ABSOLUTELY", "notes": "We want to lable the tables with all of the national parks we have visited instead of numbers"}'::jsonb),
  ('priorities', 340, '{"item": "Toasts", "rank": "5 - ABSOLUTELY", "notes": "We would probably have these mostly at the rehersal dinner. At the wedding I think it would be my dad and I? Will is not a speach giver. If my Grandpa comes he would love to give one too"}'::jsonb),
  ('priorities', 350, '{"item": "Transportation for Guests", "rank": "5 - ABSOLUTELY", "notes": "Guests will be getting drunk so we will need to have transportation for them! Also since it is destination I am not sure how many people will have cars to drive"}'::jsonb),
  ('priorities', 360, '{"item": "Unity Ceremony", "rank": "5 - ABSOLUTELY", "notes": "I want to do something. Absolutely NOT a unity candle... we have horror stories from friends weddings. I really want to plant a tree together, but I am not sure how to make that work"}'::jsonb),
  ('priorities', 370, '{"item": "Venue", "rank": "5 - ABSOLUTELY", "notes": "We want a pretty venue... willing to pay more for something that is naturally pretty"}'::jsonb),
  ('priorities', 380, '{"item": "Vibe // Theme", "rank": "5 - ABSOLUTELY", "notes": "We want a chill nature vibe, but we also want to party"}'::jsonb),
  ('priorities', 390, '{"item": "Vows", "rank": "5 - ABSOLUTELY", "notes": "We will do private vows during our first look/touch and then standard ones in the ceramony I think"}'::jsonb),
  ('priorities', 400, '{"item": "Website", "rank": "5 - ABSOLUTELY", "notes": "With it being a destination I think we need to have a good wedding website so they can easily find the information. Also, easy to direct guests to the website if they reach out to us or our parents with questions!"}'::jsonb),
  ('priorities', 410, '{"item": "Welcome Bags @ Hotel", "rank": "5 - ABSOLUTELY", "notes": "I want to have a little someting. If we are unable to find fun favors then I think we should do more here to make up for it"}'::jsonb),
  ('priorities', 420, '{"item": "Alone Time on Wedding Day", "rank": "4 - Yes", "notes": "We would love to go on a morning hike together before things get crazy, but during the festivities we want to party with our guests as much as possible. Also totally into sunset/golden hour photoshoot"}'::jsonb),
  ('priorities', 430, '{"item": "Bouquets", "rank": "4 - Yes", "notes": "I don''t need anything extravagent but I want one for me and all the bridesmaids. My aunt has offered to make these for us if we can find a flower vendor that will work with her. She is a nationally accredited florist who has been featured in many magazines so hopefully that will make them more willing"}'::jsonb),
  ('priorities', 440, '{"item": "Boutonnieres", "rank": "4 - Yes", "notes": "I like the ones that go into the pocket more than the ones that pin to the jacket. I also have a surprise for Will''s to make his a little different."}'::jsonb),
  ('priorities', 450, '{"item": "Bridal Party Attire", "rank": "4 - Yes", "notes": "I am thinking girls in emerald green and the guys in dark grey suits with emerald green ties?"}'::jsonb),
  ('priorities', 460, '{"item": "Bridal Party Gifts", "rank": "4 - Yes", "notes": "We are for sure going to get them something. Also, planning on paying for their accomidations the night before the wedding so they can stay with us."}'::jsonb),
  ('priorities', 470, '{"item": "Cake", "rank": "4 - Yes", "notes": "Will loves red velvet cake but it doesn''t have to be crazy big and we are good with sheet cakes in the back and a small one to do a cake cutting. We also don''t need a grooms cake"}'::jsonb),
  ('priorities', 480, '{"item": "Chairs", "rank": "4 - Yes", "notes": "We are good with whatever the venue provides"}'::jsonb),
  ('priorities', 490, '{"item": "Champagne toast", "rank": "4 - Yes", "notes": ""}'::jsonb),
  ('priorities', 500, '{"item": "Engagement Photos", "rank": "4 - Yes", "notes": "We would love to have our wedding photographer take engagement photos so that we can work with them before the big day"}'::jsonb);
insert into planning_rows (sheet, position, data) values
  ('priorities', 510, '{"item": "Favors", "rank": "4 - Yes", "notes": "I would love to do the cinnamon rolls, but I also could do without it if it would be too much. We want these to be intentional and minimal waste if we do them"}'::jsonb),
  ('priorities', 520, '{"item": "Flowers", "rank": "4 - Yes", "notes": "I want them but they do not need to be anything crazy!"}'::jsonb),
  ('priorities', 530, '{"item": "Guest Book", "rank": "4 - Yes", "notes": "We are thinking maybe a few poloroid cameras and a book for guests to put the pictures in and sign/write messages. Also, we want a bucket for people to put bucket list adventure recomendations for us since we love adventures."}'::jsonb),
  ('priorities', 540, '{"item": "Guest Count", "rank": "4 - Yes", "notes": "150-200, We have 300ish on our current guest list since we both come from big families and have a lot of family friends but hoping that destination will help us cut in half"}'::jsonb),
  ('priorities', 550, '{"item": "Hair + Makeup", "rank": "4 - Yes", "notes": "I am planning on getting my hair and make up done but it doesn''t have to be anything super special. I think I am planning on having my bridal party pay for their own hair and make up but not forcing them to get it done. They can have the option to do their own if they feel confident in their skills"}'::jsonb),
  ('priorities', 560, '{"item": "Officiant", "rank": "4 - Yes", "notes": "This is a controversial topic. We want one and we are thinking Christian cerimony but we come from slightly different backgrounds so are still working this out"}'::jsonb),
  ('priorities', 570, '{"item": "Rings", "rank": "4 - Yes", "notes": "My aunt works at a jewlery store and gets us good discounts so we will go to her for these"}'::jsonb),
  ('priorities', 580, '{"item": "Shoes", "rank": "4 - Yes", "notes": "Comfy shoes over cute shoes, but hoping to find comfy cute shoes"}'::jsonb),
  ('priorities', 590, '{"item": "Sticking to the Budget", "rank": "4 - Yes", "notes": "We have $60K from our parents combined for the whole weekend. Will and I have a cushion 10-15k in savings that we would be willing to spend if there is something we are dying to have, but we would love to base our whole budget on the $60K."}'::jsonb),
  ('priorities', 600, '{"item": "Ushers", "rank": "4 - Yes", "notes": "I am thinking my two little boy cousins. Since they won''t be in the actual wedding but I don''t know exactly about that idea. thinking more hand out programs vs walking to seats"}'::jsonb),
  ('priorities', 610, '{"item": "Date", "rank": "4 - Yes", "notes": "We are hoping for a Saturday wedding in the Fall of 2025 but there is no specifc weekend we are super attached to"}'::jsonb),
  ('priorities', 620, '{"item": "Ambiance", "rank": "3 - Sure", "notes": "Hoping to capture our personalities in our wedding day, but don''t feel like this needs a ton of extra attention"}'::jsonb),
  ('priorities', 630, '{"item": "Audio Quality", "rank": "3 - Sure", "notes": "We would love to have it but it is not something we would pay top dollar for."}'::jsonb),
  ('priorities', 640, '{"item": "Cake Cutting", "rank": "3 - Sure", "notes": ""}'::jsonb),
  ('priorities', 650, '{"item": "Centerpieces", "rank": "3 - Sure", "notes": "Doesn''t have to be anything crazy we are going for vibes over the top pinterest type looks"}'::jsonb),
  ('priorities', 660, '{"item": "Décor", "rank": "3 - Sure", "notes": "We just want it to look nice but we have more of a minimalist style focusing on the nature"}'::jsonb),
  ('priorities', 670, '{"item": "Dessert", "rank": "3 - Sure", "notes": "We are good with just cake"}'::jsonb),
  ('priorities', 680, '{"item": "Guest Attire", "rank": "3 - Sure", "notes": "We are thinking cocktail"}'::jsonb),
  ('priorities', 690, '{"item": "Lighting", "rank": "3 - Sure", "notes": "We like natural light in the venue. We need to look into lighting for the dance floor and stuff."}'::jsonb),
  ('priorities', 700, '{"item": "Photobooth", "rank": "3 - Sure", "notes": "We love our little photo strips that we have from friends weddings but it is not essential"}'::jsonb),
  ('priorities', 710, '{"item": "Programs", "rank": "3 - Sure", "notes": "I am thinking a little something for the whole weekend in the welcome bags? Since people will be in from out of town I think it would be nice to have an itinerary for them and things to do in the area"}'::jsonb),
  ('priorities', 720, '{"item": "Signage", "rank": "3 - Sure", "notes": "Probably leaning towards minimal on these since they seem decently wastful. However, it is important for flow sometimes"}'::jsonb),
  ('priorities', 730, '{"item": "Time of Day", "rank": "3 - Sure", "notes": "We are thinking standard wedding timeline"}'::jsonb),
  ('priorities', 740, '{"item": "Transportation for YOU", "rank": "3 - Sure", "notes": "We don''t feel strongly about this. We just need 4 wheels to get us from A to B. Also I am like 100% sure both sets of parents and us will be driving to the wedding so we will have cars to get Will and I around"}'::jsonb),
  ('priorities', 750, '{"item": "Weather", "rank": "3 - Sure", "notes": "We will be okay with whatever mother nature throws at us"}'::jsonb),
  ('priorities', 760, '{"item": "Bridal Accessories", "rank": "2 - Maybe", "notes": "I think just earrings no other accessories"}'::jsonb),
  ('priorities', 770, '{"item": "Calligraphy", "rank": "2 - Maybe", "notes": "Will''s sister would be able to help with this if we find something we really like but we don''t feel very strongly about it"}'::jsonb),
  ('priorities', 780, '{"item": "Formality // Tradition", "rank": "2 - Maybe", "notes": "We both come from traditional families, but I wouldn''t say it is a huge priority for us."}'::jsonb),
  ('priorities', 790, '{"item": "Linens", "rank": "2 - Maybe", "notes": "We are good with just white standard linens"}'::jsonb),
  ('priorities', 800, '{"item": "Premarital Counseling", "rank": "2 - Maybe", "notes": "We haven''t looked into this much"}'::jsonb),
  ('priorities', 810, '{"item": "Rentals", "rank": "2 - Maybe", "notes": "Open to renting or buying depending on the cost of items"}'::jsonb),
  ('priorities', 820, '{"item": "Veil", "rank": "2 - Maybe", "notes": "Undecided but if I do it''ll be something cheap from amazon"}'::jsonb),
  ('priorities', 830, '{"item": "Videographer", "rank": "2 - Maybe", "notes": "I want one, but they are expensive so if we can''t make it work then I am thinking we just give both bridal parties cheap video cameras and do a vlog type thing"}'::jsonb),
  ('priorities', 840, '{"item": "Accommodations for Guests", "rank": "1 - Nah", "notes": "Planning on having information for a hotels/airbnbs in the area for guests to book on their own. Having a hotel block for guests to be picked up by bus from a central location is our plan"}'::jsonb),
  ('priorities', 850, '{"item": "Band", "rank": "1 - Nah", "notes": "We like DJs more"}'::jsonb),
  ('priorities', 860, '{"item": "Beauty Routine", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 870, '{"item": "Bouquet Toss", "rank": "1 - Nah", "notes": "I don''t think I want to toss my bouquet"}'::jsonb),
  ('priorities', 880, '{"item": "Cake Knife + Server", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 890, '{"item": "Cake Topper", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 900, '{"item": "Church", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 910, '{"item": "Communion", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 920, '{"item": "Dinner Menus", "rank": "1 - Nah", "notes": "If we end up doing these I think just one per table or a big menu at the start of the buffet would be good"}'::jsonb),
  ('priorities', 930, '{"item": "Engagement Announcements", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 940, '{"item": "Engagement Party", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 950, '{"item": "Escort/Place Cards", "rank": "1 - Nah", "notes": "We are thinking just a big sign that has everyone listed out and the table they are at"}'::jsonb),
  ('priorities', 960, '{"item": "Flower Girl // Ring Bearer", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 970, '{"item": "Garter Toss", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 980, '{"item": "Groom’s Cake", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 990, '{"item": "Head Table", "rank": "1 - Nah", "notes": "Thinking of just having our bridal party sit with their plus ones and us at a sweetheart table"}'::jsonb),
  ('priorities', 1000, '{"item": "Lounge Space", "rank": "1 - Nah", "notes": ""}'::jsonb);
insert into planning_rows (sheet, position, data) values
  ('priorities', 1010, '{"item": "Money Dance", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 1020, '{"item": "Personal Toasting Glasses", "rank": "1 - Nah", "notes": ""}'::jsonb),
  ('priorities', 1030, '{"item": "Utensils", "rank": "1 - Nah", "notes": "We are good with the standard utensils"}'::jsonb);

-- wedding_party: 30 rows
insert into planning_rows (sheet, position, data) values
  ('wedding_party', 10, '{"group": "Couple", "slot": "Partner #1", "name": "Robin Beattie", "role": "BRIDE!!", "phone": "(281) 731-6464", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 20, '{"group": "Couple", "slot": "Partner #2", "name": "Andy Horton", "role": "Groom", "phone": "(940) 367-2358", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 30, '{"group": "Immediate Family", "slot": "Parents of Partner #1", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 40, '{"group": "Immediate Family", "slot": "Parents of Partner #2", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 50, '{"group": "Immediate Family", "slot": "Siblings", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 60, '{"group": "Immediate Family", "slot": "Step/Other Parents", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 70, '{"group": "Grandparents", "slot": "Grandparents of Partner #1", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 80, '{"group": "Grandparents", "slot": "Grandparents of Partner #2", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 90, '{"group": "Wedding Party", "slot": "Maid of Honor", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 100, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 110, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 120, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 130, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 140, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 150, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 160, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 170, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 180, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 190, '{"group": "Wedding Party", "slot": "Bridesmaid", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 200, '{"group": "Wedding Party", "slot": "Best Man", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 210, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 220, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 230, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 240, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 250, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 260, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 270, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 280, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 290, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb),
  ('wedding_party', 300, '{"group": "Wedding Party", "slot": "Groomsman", "name": "", "role": "", "phone": "", "email": "", "notes": "", "gifts": ""}'::jsonb);

-- timeline: 26 rows
insert into planning_rows (sheet, position, data) values
  ('timeline', 10, '{"time": "", "item": "Night Before: Ceremony Rehearsal", "vendors": "Wedding Party, Venue, Planner", "notes": ""}'::jsonb),
  ('timeline', 20, '{"time": "", "item": "Night Before: Rehearsal Dinner", "vendors": "Wedding Party, Venue, Planner", "notes": ""}'::jsonb),
  ('timeline', 30, '{"time": "2:00 PM", "item": "Venue Access Begins", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 40, '{"time": "", "item": "Hair & Makeup Schedule", "vendors": "Wedding Party, Venue, Planner, HMUA", "notes": ""}'::jsonb),
  ('timeline', 50, '{"time": "", "item": "Partner #1 Arrives at Venue", "vendors": "Wedding Party, Venue, Planner, HMUA", "notes": ""}'::jsonb),
  ('timeline', 60, '{"time": "", "item": "Partner #2 Arrives at Venue", "vendors": "Wedding Party, Venue, Planner, HMUA", "notes": ""}'::jsonb),
  ('timeline', 70, '{"time": "2:00pm-3:30pm", "item": "Venue Setup", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 80, '{"time": "TBD", "item": "First Look", "vendors": "Photo, Video, Venue, Planner, Wedding Party, HMUA", "notes": ""}'::jsonb),
  ('timeline', 90, '{"time": "TBD", "item": "Pre Ceremony Photos", "vendors": "Photo, Video, Venue, Planner, Wedding Party, HMUA", "notes": ""}'::jsonb),
  ('timeline', 100, '{"time": "3:30 PM", "item": "Prelude Begins + Guest Begin to Arrive (30 minutes prior to ceremony)", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 110, '{"time": "4:00 PM", "item": "Ceremony", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 120, '{"time": "4:30pm-5:30pm", "item": "Cocktail Hour + Photos", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 130, '{"time": "5:30 PM", "item": "Grand Entrance", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 140, '{"time": "5:30 PM", "item": "First Dance", "vendors": "", "notes": ""}'::jsonb),
  ('timeline', 150, '{"time": "5:45pm/6:00pm", "item": "Dinner", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 160, '{"time": "", "item": "Toasts", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 170, '{"time": "", "item": "Dessert", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 180, '{"time": "", "item": "Reception", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 190, '{"time": "", "item": "Parent/Other Special Dances", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 200, '{"time": "", "item": "Cake Cutting", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 210, '{"time": "", "item": "Bouquet/Garter Toss", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 220, '{"time": "", "item": "Last Song/Dance", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 230, '{"time": "9:15 PM", "item": "Sendoff", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 240, '{"time": "9:15 PM", "item": "Event Ends- lights on", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 250, '{"time": "9:15 PM", "item": "Event Cleanup Begins", "vendors": "ALL", "notes": ""}'::jsonb),
  ('timeline', 260, '{"time": "10:00 PM", "item": "Venue Access Ends", "vendors": "ALL", "notes": ""}'::jsonb);

-- packing: 111 rows
insert into planning_rows (sheet, position, data) values
  ('packing', 10, '{"category": "Personal Items", "item": "Getting Ready Outfit + Shoes", "packed": false, "notes": ""}'::jsonb),
  ('packing', 20, '{"category": "Personal Items", "item": "Undergarments", "packed": false, "notes": ""}'::jsonb),
  ('packing', 30, '{"category": "Personal Items/Details", "item": "Dress", "packed": false, "notes": ""}'::jsonb),
  ('packing', 40, '{"category": "Personal Items/Details", "item": "Nice Hanger for Photos!", "packed": false, "notes": ""}'::jsonb),
  ('packing', 50, '{"category": "Personal Items/Details", "item": "Suit, tie, vest, belt, etc.", "packed": false, "notes": ""}'::jsonb),
  ('packing', 60, '{"category": "Personal Items/Details", "item": "Shoes", "packed": false, "notes": ""}'::jsonb),
  ('packing', 70, '{"category": "Personal Items", "item": "Extra Shoes (comfy ones)", "packed": false, "notes": ""}'::jsonb),
  ('packing', 80, '{"category": "Personal Items", "item": "Hankerchief", "packed": false, "notes": ""}'::jsonb),
  ('packing', 90, '{"category": "Personal Items", "item": "Touch-up Makeup Kit", "packed": false, "notes": ""}'::jsonb),
  ('packing', 100, '{"category": "Personal Items", "item": "Hair Brush + Comb", "packed": false, "notes": ""}'::jsonb),
  ('packing', 110, '{"category": "Personal Items", "item": "Hair Supplies- extra bobby pins, hairspray, hair gel, etc.", "packed": false, "notes": ""}'::jsonb),
  ('packing', 120, '{"category": "Personal Items", "item": "Accessories- jewelry, watch, tie, cufflinks, pins, veil, something old, new, borrowed, blue, etc.", "packed": false, "notes": ""}'::jsonb),
  ('packing', 130, '{"category": "Personal Items", "item": "Hair Accessories", "packed": false, "notes": ""}'::jsonb),
  ('packing', 140, '{"category": "Personal Items", "item": "Extra Outfit- if you''re changing later in the evening", "packed": false, "notes": ""}'::jsonb),
  ('packing', 150, '{"category": "Personal Items/Details", "item": "Perfume + Cologne", "packed": false, "notes": ""}'::jsonb),
  ('packing', 160, '{"category": "Personal Items", "item": "Purse + Bag", "packed": false, "notes": ""}'::jsonb),
  ('packing', 170, '{"category": "Personal Items", "item": "Steamer", "packed": false, "notes": ""}'::jsonb),
  ('packing', 180, '{"category": "Details", "item": "Rings", "packed": false, "notes": ""}'::jsonb),
  ('packing', 190, '{"category": "Details", "item": "Special Accessories you want photographed from the above list, or other things!", "packed": false, "notes": ""}'::jsonb),
  ('packing', 200, '{"category": "Details", "item": "2 Invitation Suites + Envelopes", "packed": false, "notes": ""}'::jsonb),
  ('packing', 210, '{"category": "Details", "item": "Ring Box(es)", "packed": false, "notes": ""}'::jsonb),
  ('packing', 220, '{"category": "Gifts", "item": "Any gifts for your partner, family, or wedding party", "packed": false, "notes": ""}'::jsonb),
  ('packing', 230, '{"category": "Gifts", "item": "Letter to your spouse", "packed": false, "notes": ""}'::jsonb),
  ('packing', 240, '{"category": "Logistics", "item": "Seating Chart- print a few paper copies", "packed": false, "notes": "Print a few copies. If you''ve hired a planner we will bring these items."}'::jsonb),
  ('packing', 250, '{"category": "Logistics", "item": "Floor Plan- print a few copies", "packed": false, "notes": "Print a few copies. If you''ve hired a planner we will bring these items."}'::jsonb),
  ('packing', 260, '{"category": "Logistics", "item": "Day of Timelines- print a few copies", "packed": false, "notes": "Print a few copies. If you''ve hired a planner we will bring these items."}'::jsonb),
  ('packing', 270, '{"category": "Logistics", "item": "List of All Vendors + Contact Info- print a few copies", "packed": false, "notes": "Print a few copies. If you''ve hired a planner we will bring these items."}'::jsonb),
  ('packing', 280, '{"category": "Logistics", "item": "Venue Requirements + Instructions for Clean Up- print a few copies", "packed": false, "notes": "Print a few copies. If you''ve hired a planner we will bring these items."}'::jsonb),
  ('packing', 290, '{"category": "Logistics", "item": "Directional Signage", "packed": false, "notes": ""}'::jsonb),
  ('packing', 300, '{"category": "Logistics", "item": "Labeled Envelopes with Vendor Tips", "packed": false, "notes": ""}'::jsonb),
  ('packing', 310, '{"category": "Logistics", "item": "Pen + Notepad", "packed": false, "notes": ""}'::jsonb),
  ('packing', 320, '{"category": "Logistics", "item": "Make Sure Everyone has an ID on them/at the venue as needed", "packed": false, "notes": ""}'::jsonb),
  ('packing', 330, '{"category": "Ceremony", "item": "Aisle Runner/decor", "packed": false, "notes": ""}'::jsonb),
  ('packing', 340, '{"category": "Ceremony", "item": "Arch/Structure", "packed": false, "notes": ""}'::jsonb),
  ('packing', 350, '{"category": "Ceremony", "item": "Ceremony Florals", "packed": false, "notes": ""}'::jsonb),
  ('packing', 360, '{"category": "Ceremony", "item": "Arch Piece", "packed": false, "notes": ""}'::jsonb),
  ('packing', 370, '{"category": "Ceremony", "item": "Pedastals", "packed": false, "notes": ""}'::jsonb),
  ('packing', 380, '{"category": "Ceremony", "item": "Ceremony Programs/things for each chair", "packed": false, "notes": ""}'::jsonb),
  ('packing', 390, '{"category": "Ceremony", "item": "Main Bouquet/Bout", "packed": false, "notes": ""}'::jsonb),
  ('packing', 400, '{"category": "Ceremony", "item": "Religious Items", "packed": false, "notes": ""}'::jsonb),
  ('packing', 410, '{"category": "Ceremony", "item": "Wedding Party Florals (bouquets, bouts, corsages, flower petals + baskets, etc.", "packed": false, "notes": ""}'::jsonb),
  ('packing', 420, '{"category": "Ceremony", "item": "Ring Bearer Supplies", "packed": false, "notes": ""}'::jsonb),
  ('packing', 430, '{"category": "Ceremony", "item": "Unity Items", "packed": false, "notes": ""}'::jsonb),
  ('packing', 440, '{"category": "Ceremony", "item": "Table + Linen as needed", "packed": false, "notes": ""}'::jsonb),
  ('packing', 450, '{"category": "Ceremony", "item": "Ceremony Signage- welcome sign, seating assignments, reserved signs, etc.", "packed": false, "notes": ""}'::jsonb),
  ('packing', 460, '{"category": "Ceremony", "item": "Marriage License", "packed": false, "notes": ""}'::jsonb),
  ('packing', 470, '{"category": "Ceremony", "item": "Mic + Stand", "packed": false, "notes": ""}'::jsonb),
  ('packing', 480, '{"category": "Ceremony", "item": "Music + Speakers", "packed": false, "notes": ""}'::jsonb),
  ('packing', 490, '{"category": "Ceremony", "item": "Copy of Vows/Vow Books", "packed": false, "notes": ""}'::jsonb),
  ('packing', 500, '{"category": "Ceremony", "item": "Officiant Notes/Book", "packed": false, "notes": ""}'::jsonb);
insert into planning_rows (sheet, position, data) values
  ('packing', 510, '{"category": "Food + Drink", "item": "Bottled Water", "packed": false, "notes": ""}'::jsonb),
  ('packing', 520, '{"category": "Food + Drink", "item": "Champagne or drink of choice + Glasses for getting ready", "packed": false, "notes": ""}'::jsonb),
  ('packing', 530, '{"category": "Food + Drink", "item": "Snacks", "packed": false, "notes": ""}'::jsonb),
  ('packing', 540, '{"category": "Food + Drink", "item": "Make Breakfast + Lunch Plans ahead of time", "packed": false, "notes": ""}'::jsonb),
  ('packing', 550, '{"category": "Reception", "item": "Welcome Sign + Easel", "packed": false, "notes": ""}'::jsonb),
  ('packing', 560, '{"category": "Reception", "item": "Card Box", "packed": false, "notes": ""}'::jsonb),
  ('packing', 570, '{"category": "Reception", "item": "Cards + Gifts Sign", "packed": false, "notes": ""}'::jsonb),
  ('packing', 580, '{"category": "Reception", "item": "Guest Book or alternative sign in option", "packed": false, "notes": ""}'::jsonb),
  ('packing', 590, '{"category": "Reception", "item": "Good quality pens + markers (make sure they work with your book!!)", "packed": false, "notes": ""}'::jsonb),
  ('packing', 600, '{"category": "Reception", "item": "Guest Book Sign", "packed": false, "notes": ""}'::jsonb),
  ('packing', 610, '{"category": "Reception", "item": "Champagne Flutes", "packed": false, "notes": ""}'::jsonb),
  ('packing', 620, '{"category": "Reception", "item": "Bar Sign", "packed": false, "notes": ""}'::jsonb),
  ('packing', 630, '{"category": "Reception", "item": "Cake Stand", "packed": false, "notes": ""}'::jsonb),
  ('packing', 640, '{"category": "Reception", "item": "Cake Topper", "packed": false, "notes": ""}'::jsonb),
  ('packing', 650, '{"category": "Reception", "item": "Cake Knife + Server", "packed": false, "notes": ""}'::jsonb),
  ('packing', 660, '{"category": "Reception", "item": "Disposables for cake service (if not included with the catering company)", "packed": false, "notes": ""}'::jsonb),
  ('packing', 670, '{"category": "Reception", "item": "Seating Chart and/or Place Cards", "packed": false, "notes": ""}'::jsonb),
  ('packing', 680, '{"category": "Reception", "item": "Favors", "packed": false, "notes": ""}'::jsonb),
  ('packing', 690, '{"category": "Reception", "item": "Garter", "packed": false, "notes": ""}'::jsonb),
  ('packing', 700, '{"category": "Reception", "item": "Toss Bouquet", "packed": false, "notes": ""}'::jsonb),
  ('packing', 710, '{"category": "Reception", "item": "Photos to Display", "packed": false, "notes": ""}'::jsonb),
  ('packing', 720, '{"category": "Reception", "item": "Personalized items (cocktail napkins, koozies, etc).", "packed": false, "notes": ""}'::jsonb),
  ('packing', 730, '{"category": "Reception", "item": "Sendoff Supplies (ie. sparklers, something to hold them, bucket for water, lighters)", "packed": false, "notes": ""}'::jsonb),
  ('packing', 740, '{"category": "Reception", "item": "Table Numbers", "packed": false, "notes": ""}'::jsonb),
  ('packing', 750, '{"category": "Reception", "item": "Linens", "packed": false, "notes": ""}'::jsonb),
  ('packing', 760, '{"category": "Reception", "item": "Menu Card or Sign", "packed": false, "notes": ""}'::jsonb),
  ('packing', 770, '{"category": "Reception", "item": "Place Settings- plate(s), napkin, cutlery, glassware", "packed": false, "notes": ""}'::jsonb),
  ('packing', 780, '{"category": "Reception", "item": "Table Decor- candles, florals, photo frames, etc.", "packed": false, "notes": ""}'::jsonb),
  ('packing', 790, '{"category": "Reception", "item": "Memorial Items", "packed": false, "notes": ""}'::jsonb),
  ('packing', 800, '{"category": "Reception", "item": "Neon Sign", "packed": false, "notes": ""}'::jsonb),
  ('packing', 810, '{"category": "Reception", "item": "Backdrop/Photo Area", "packed": false, "notes": ""}'::jsonb),
  ('packing', 820, '{"category": "Emergency Kit", "item": "Phone Charger(s)", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 830, '{"category": "Emergency Kit", "item": "Medicine", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 840, '{"category": "Emergency Kit", "item": "Mini Sewing Kit", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 850, '{"category": "Emergency Kit", "item": "Heel Protectors", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 860, '{"category": "Emergency Kit", "item": "Tide to Go Pen", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 870, '{"category": "Emergency Kit", "item": "Deodorant", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 880, '{"category": "Emergency Kit", "item": "Perfume", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 890, '{"category": "Emergency Kit", "item": "Toothbrush + toothpaste", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 900, '{"category": "Emergency Kit", "item": "Breath Mints", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 910, '{"category": "Emergency Kit", "item": "Hair Ties + Bobby Pins", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 920, '{"category": "Emergency Kit", "item": "Tampons + Pads", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 930, '{"category": "Emergency Kit", "item": "Sunscreen", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 940, '{"category": "Emergency Kit", "item": "Small Mirror", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 950, '{"category": "Emergency Kit", "item": "Tissues", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 960, '{"category": "Emergency Kit", "item": "Bandaids", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 970, '{"category": "Emergency Kit", "item": "Extra Floral Pins", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 980, '{"category": "Emergency Kit", "item": "Safety Pins", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 990, '{"category": "Emergency Kit", "item": "Mirror", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1000, '{"category": "Emergency Kit", "item": "Nail Polish (to help fix a manicure)", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb);
insert into planning_rows (sheet, position, data) values
  ('packing', 1010, '{"category": "Emergency Kit", "item": "Makeup Wipes/Remover", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1020, '{"category": "Emergency Kit", "item": "Baby Powder", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1030, '{"category": "Emergency Kit", "item": "Tweezers", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1040, '{"category": "Emergency Kit", "item": "Tape", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1050, '{"category": "Emergency Kit", "item": "Scissors", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1060, '{"category": "Emergency Kit", "item": "Lint Brush", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1070, '{"category": "Emergency Kit", "item": "Extra Cash", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1080, '{"category": "Emergency Kit", "item": "Portable Phone Charger", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1090, '{"category": "Emergency Kit", "item": "Batteries", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1100, '{"category": "Emergency Kit", "item": "Extra Water + Snacks", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb),
  ('packing', 1110, '{"category": "Emergency Kit", "item": "Gallon Bags + Tupperware for extra food/cake", "packed": false, "notes": "Your planner will provide an emergency kit with our team with the majority of these items"}'::jsonb);

-- budget items: 27 rows
insert into budget_items (name, estimated, notes, position) values
  ('Wedding Venue', 7750.0, null, 10),
  ('Additional Venue Items- Linens', 0, null, 20),
  ('Catering + Rentals + Napkins', 14700.0, null, 30),
  ('Bar Service', 3995.0, null, 40),
  ('Alcohol', 0, null, 50),
  ('Planner', 5500.0, null, 60),
  ('Photographer', 4278.0, null, 70),
  ('Videographer', 3400.0, null, 80),
  ('Wedding Cake', 800.0, null, 90),
  ('Florals', 5500.0, null, 100),
  ('DJ', 3500.0, null, 110),
  ('Hair & Makeup', 1000.0, null, 120),
  ('Wedding Dress', 1500.0, null, 130),
  ('Wedding Suit/Tux', 1000.0, null, 140),
  ('Alterations', 500.0, null, 150),
  ('Attire Accessories', 500.0, null, 160),
  ('Save the Dates', 360.0, null, 170),
  ('Stationery', 600.0, null, 180),
  ('Stamps', 300.0, null, 190),
  ('Photo Prints/Signage', 0, null, 200),
  ('Marriage License', 50.0, null, 210),
  ('Rentals', 0, null, 220),
  ('Decor Items', 0, null, 230),
  ('Accommodations (Bridal Party & Us)', 2800.0, null, 240),
  ('Rehersal Dinner', 14000.0, null, 250),
  ('Welcome Bags', 0, null, 260),
  ('Welcome Party', 0, null, 270);

-- budget settings (from the Simple Budget sheet — edit in the Budget tab)
insert into planning_settings (key, value) values
  ('budget_goal', '60000'),
  ('monthly_contribution', '0'),
  ('family_contribution', '60000'),
  ('savings_contribution', '0')
on conflict (key) do nothing;
